apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    {{- include "flowers.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  type: ClusterIP
  ports:
  - name: db
    port: 5432
    targetPort: db
  selector:
    app.kubernetes.io/name: db
    app.kubernetes.io/instance: {{ .Release.Name }}
