apiVersion: v1
kind: Secret
metadata:
  name: db
  labels:
    app.kubernetes.io/component: db
    {{- include "flowers.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.db.password }}
  db-password:  {{ .Values.db.password | b64enc | quote }}
  {{- else }}
  db-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
