apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    {{- include "flowers.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  serviceName: db
  selector:
    matchLabels:
      app.kubernetes.io/name: db
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: postgress
        image: postgres:12.0-alpine
        env:
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: okteto
          - name: POSTGRES_DB
            value: prediction
        ports:
        - name: db
          containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: 
        resources:
          {}
      volumes:
      - name: data
        emptyDir: {}